In [1]:
import tushare as ts
import pandas as pd
import numpy as np
import baostock as bs
import datetime
import os
import talib

## 部分标底计算 相关指标

### 需求

1. 标底
    - 比亚迪
    - 五粮液
    - 恒生电子
    - 赛力斯

2. 需求
    - 比如一直运行在20日线上方 / 或者周线上方 / 10周线
    - 日K出现负值后 5天 10天 30天的收益
    - 20日线可以换成60日生命线
    - KDJ 的J值 负值 / 也可以划分范围 0~-5 -5~-10 / 先按负值先跑

3. 这套体系其实就是在右侧趋势还在的情况下，指标超买了，赚取指标修正的收益

In [2]:
"""
2024-1至2025-2的沪深300数据
不足够来支撑的话增加数据
"""
data_df = pd.DataFrame(pd.read_csv("/home/kennys/MineX/QuantTrading/dataset/沪深300-2024年1月至2025年2月数据.csv"))
data_df

,Unnamed: 0,date,code,open,high,low,close,preclose,volume,amount,turn
0,0,2024-01-02,sh.600000,6.63,6.65,6.60,6.60,6.62,22066700.0,1.460663e+08,0.0752
1,1,2024-01-03,sh.600000,6.59,6.65,6.59,6.64,6.60,18203654.0,1.206397e+08,0.0620
2,2,2024-01-04,sh.600000,6.64,6.67,6.55,6.62,6.64,28885978.0,1.905806e+08,0.0984
3,3,2024-01-05,sh.600000,6.60,6.76,6.59,6.68,6.62,44421387.0,2.969769e+08,0.1513
4,4,2024-01-08,sh.600000,6.68,6.71,6.56,6.59,6.68,37520337.0,2.479778e+08,0.1278
...,...,...,...,...,...,...,...,...,...,...,...
83395,83395,2025-02-24,sz.301269,117.31,119.48,115.48,117.76,117.31,6239560.0,7.320926e+08,2.3786
83396,83396,2025-02-25,sz.301269,115.80,120.83,114.40,118.11,117.76,7596517.0,8.936182e+08,2.8959
83397,83397,2025-02-26,sz.301269,118.18,118.51,114.28,117.49,118.11,7569108.0,8.792310e+08,2.8854
83398,83398,2025-02-27,sz.301269,116.98,117.63,112.25,114.09,117.49,6267180.0,7.182731e+08,2.3891
83399,83399,2025-02-28,sz.301269,113.00,113.80,106.09,107.14,114.09,5876698.0,6.411158e+08,2.2403